// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chapter.sql

package db

import (
	"context"
)

const addChapter = `-- name: AddChapter :one
INSERT INTO chapters (
  title,
  subtitle,
  description
) VALUES (
  $1, $2, $3
)
RETURNING id, title, subtitle, description
`

type AddChapterParams struct {
	Title       string
	Subtitle    string
	Description string
}

func (q *Queries) AddChapter(ctx context.Context, arg AddChapterParams) (Chapter, error) {
	row := q.db.QueryRowContext(ctx, addChapter, arg.Title, arg.Subtitle, arg.Description)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.Description,
	)
	return i, err
}

const getChapter = `-- name: GetChapter :one
SELECT id, title, subtitle, description
FROM chapters
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetChapter(ctx context.Context, id int64) (Chapter, error) {
	row := q.db.QueryRowContext(ctx, getChapter, id)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.Description,
	)
	return i, err
}

const listChapters = `-- name: ListChapters :many
SELECT id, title, subtitle, description
FROM chapters
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListChaptersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListChapters(ctx context.Context, arg ListChaptersParams) ([]Chapter, error) {
	rows, err := q.db.QueryContext(ctx, listChapters, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chapter{}
	for rows.Next() {
		var i Chapter
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChapter = `-- name: UpdateChapter :one
UPDATE chapters
SET
  title       = COALESCE($2, title),
  subtitle    = COALESCE($3, subtitle),
  description = COALESCE($4, description)
WHERE id = $1
RETURNING id, title, subtitle, description
`

type UpdateChapterParams struct {
	ID          int64
	Title       string
	Subtitle    string
	Description string
}

func (q *Queries) UpdateChapter(ctx context.Context, arg UpdateChapterParams) (Chapter, error) {
	row := q.db.QueryRowContext(ctx, updateChapter,
		arg.ID,
		arg.Title,
		arg.Subtitle,
		arg.Description,
	)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.Description,
	)
	return i, err
}
