// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chapter.sql

package db

import (
	"context"
)

const addChapter = `-- name: AddChapter :one
INSERT INTO chapters (
  name
) VALUES (
  $1
)
RETURNING id, name
`

func (q *Queries) AddChapter(ctx context.Context, name string) (Chapter, error) {
	row := q.db.QueryRowContext(ctx, addChapter, name)
	var i Chapter
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getChapter = `-- name: GetChapter :one
SELECT id, name
FROM chapters
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetChapter(ctx context.Context, id int64) (Chapter, error) {
	row := q.db.QueryRowContext(ctx, getChapter, id)
	var i Chapter
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listChapters = `-- name: ListChapters :many
SELECT id, name
FROM chapters
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListChaptersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListChapters(ctx context.Context, arg ListChaptersParams) ([]Chapter, error) {
	rows, err := q.db.QueryContext(ctx, listChapters, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chapter{}
	for rows.Next() {
		var i Chapter
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
