// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Chapter struct {
	ID   int64
	Name string
}

type Sloka struct {
	ID              int64
	ChapterID       int64
	Sloka           string
	Transliteration string
	Purport         sql.NullString
	Explanation     sql.NullString
}
