// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sloka.sql

package db

import (
	"context"
)

const getSloka = `-- name: GetSloka :one
SELECT id, chapter_id, sloka, transliteration, purport, explanation
FROM slokas
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSloka(ctx context.Context, id int64) (Sloka, error) {
	row := q.db.QueryRowContext(ctx, getSloka, id)
	var i Sloka
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.Sloka,
		&i.Transliteration,
		&i.Purport,
		&i.Explanation,
	)
	return i, err
}

const listSlokasByChapter = `-- name: ListSlokasByChapter :many
SELECT id, chapter_id, sloka, transliteration, purport, explanation
FROM slokas
WHERE chapter_id = $1
ORDER BY id
`

func (q *Queries) ListSlokasByChapter(ctx context.Context, chapterID int64) ([]Sloka, error) {
	rows, err := q.db.QueryContext(ctx, listSlokasByChapter, chapterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sloka{}
	for rows.Next() {
		var i Sloka
		if err := rows.Scan(
			&i.ID,
			&i.ChapterID,
			&i.Sloka,
			&i.Transliteration,
			&i.Purport,
			&i.Explanation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
