// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sloka.sql

package db

import (
	"context"
	"database/sql"
)

const addSloka = `-- name: AddSloka :one
INSERT INTO slokas (
  chapter_id,
  sloka,
  transliteration,
  purport,
  explanation
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, chapter_id, sloka, transliteration, purport, explanation
`

type AddSlokaParams struct {
	ChapterID       int64
	Sloka           string
	Transliteration string
	Purport         sql.NullString
	Explanation     sql.NullString
}

func (q *Queries) AddSloka(ctx context.Context, arg AddSlokaParams) (Sloka, error) {
	row := q.db.QueryRowContext(ctx, addSloka,
		arg.ChapterID,
		arg.Sloka,
		arg.Transliteration,
		arg.Purport,
		arg.Explanation,
	)
	var i Sloka
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.Sloka,
		&i.Transliteration,
		&i.Purport,
		&i.Explanation,
	)
	return i, err
}

const getSloka = `-- name: GetSloka :one
SELECT id, chapter_id, sloka, transliteration, purport, explanation
FROM slokas
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSloka(ctx context.Context, id int64) (Sloka, error) {
	row := q.db.QueryRowContext(ctx, getSloka, id)
	var i Sloka
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.Sloka,
		&i.Transliteration,
		&i.Purport,
		&i.Explanation,
	)
	return i, err
}

const listSlokasByChapter = `-- name: ListSlokasByChapter :many
SELECT id, chapter_id, sloka, transliteration, purport, explanation
FROM slokas
WHERE chapter_id = $1
ORDER BY id
`

func (q *Queries) ListSlokasByChapter(ctx context.Context, chapterID int64) ([]Sloka, error) {
	rows, err := q.db.QueryContext(ctx, listSlokasByChapter, chapterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sloka{}
	for rows.Next() {
		var i Sloka
		if err := rows.Scan(
			&i.ID,
			&i.ChapterID,
			&i.Sloka,
			&i.Transliteration,
			&i.Purport,
			&i.Explanation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSloka = `-- name: UpdateSloka :one
UPDATE slokas
SET
  sloka           = COALESCE($2, sloka),
  transliteration = COALESCE($3, transliteration),
  purport         = COALESCE($4, purport),
  explanation     = COALESCE($5, explanation)
WHERE id = $1
RETURNING id, chapter_id, sloka, transliteration, purport, explanation
`

type UpdateSlokaParams struct {
	ID              int64
	Sloka           string
	Transliteration string
	Purport         sql.NullString
	Explanation     sql.NullString
}

func (q *Queries) UpdateSloka(ctx context.Context, arg UpdateSlokaParams) (Sloka, error) {
	row := q.db.QueryRowContext(ctx, updateSloka,
		arg.ID,
		arg.Sloka,
		arg.Transliteration,
		arg.Purport,
		arg.Explanation,
	)
	var i Sloka
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.Sloka,
		&i.Transliteration,
		&i.Purport,
		&i.Explanation,
	)
	return i, err
}
